<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-SMR1PUS" name="Selenium.java.LearningAttributesLTESTNG" tests="3" failures="1" timestamp="2020-03-24T12:47:54 IST" time="0.023" errors="0">
  <testcase name="TestC" time="0.001" classname="Selenium.java.LearningAttributesLTESTNG"/>
  <system-out/>
  <testcase name="TestB" time="0.020" classname="Selenium.java.LearningAttributesLTESTNG">
    <failure type="java.lang.AssertionError" message="expected [yahoo] but found [yahoo1]">
      <![CDATA[java.lang.AssertionError: expected [yahoo] but found [yahoo1]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at Selenium.java.LearningAttributesLTESTNG.TestB(LearningAttributesLTESTNG.java:17)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:68)
at org.testng.internal.InvokeMethodRunnable.call(InvokeMethodRunnable.java:13)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- TestB -->
  <system-out/>
  <testcase name="TestA" time="0.002" classname="Selenium.java.LearningAttributesLTESTNG"/>
  <system-out/>
</testsuite> <!-- Selenium.java.LearningAttributesLTESTNG -->
